document.write("<form id=\"search\">\n");
document.write("<input type=\"text\" id=\"domain-name\" name=\"domain\">\n");
document.write("<input type=\"text\" id=\"domain-d\" name=\"dummy\" style=\"display:none;\">\n");
document.write("<select id=\"domain-ext\" name=\"ext\">\n");
document.write("<option>.eu.org</option>\n");
document.write("<option>.asso.eu.org</option>\n");
document.write("<option>.edu.eu.org</option>\n");
document.write("<option>.int.eu.org</option>\n");
document.write("<option>.net.eu.org</option>\n");
document.write("<option>.al.eu.org</option>\n");
document.write("<option>.at.eu.org</option>\n");
document.write("<option>.au.eu.org</option>\n");
document.write("<option>.be.eu.org</option>\n");
document.write("<option>.bg.eu.org</option>\n");
document.write("<option>.ca.eu.org</option>\n");
document.write("<option>.cd.eu.org</option>\n");
document.write("<option>.ch.eu.org</option>\n");
document.write("<option>.cn.eu.org</option>\n");
document.write("<option>.cy.eu.org</option>\n");
document.write("<option>.cz.eu.org</option>\n");
document.write("<option>.de.eu.org</option>\n");
document.write("<option>.dk.eu.org</option>\n");
document.write("<option>.ee.eu.org</option>\n");
document.write("<option>.es.eu.org</option>\n");
document.write("<option>.fi.eu.org</option>\n");
document.write("<option>.fr.eu.org</option>\n");
document.write("<option>.gr.eu.org</option>\n");
document.write("<option>.hr.eu.org</option>\n");
document.write("<option>.hu.eu.org</option>\n");
document.write("<option>.ie.eu.org</option>\n");
document.write("<option>.il.eu.org</option>\n");
document.write("<option>.in.eu.org</option>\n");
document.write("<option>.is.eu.org</option>\n");
document.write("<option>.it.eu.org</option>\n");
document.write("<option>.jp.eu.org</option>\n");
document.write("<option>.kr.eu.org</option>\n");
document.write("<option>.lt.eu.org</option>\n");
document.write("<option>.lu.eu.org</option>\n");
document.write("<option>.lv.eu.org</option>\n");
document.write("<option>.mc.eu.org</option>\n");
document.write("<option>.me.eu.org</option>\n");
document.write("<option>.mk.eu.org</option>\n");
document.write("<option>.mt.eu.org</option>\n");
document.write("<option>.my.eu.org</option>\n");
document.write("<option>.ng.eu.org</option>\n");
document.write("<option>.nl.eu.org</option>\n");
document.write("<option>.no.eu.org</option>\n");
document.write("<option>.nz.eu.org</option>\n");
document.write("<option>.pl.eu.org</option>\n");
document.write("<option>.pt.eu.org</option>\n");
document.write("<option>.ro.eu.org</option>\n");
document.write("<option>.ru.eu.org</option>\n");
document.write("<option>.se.eu.org</option>\n");
document.write("<option>.si.eu.org</option>\n");
document.write("<option>.sk.eu.org</option>\n");
document.write("<option>.tr.eu.org</option>\n");
document.write("<option>.uk.eu.org</option>\n");
document.write("<option>.us.eu.org</option>\n");
document.write("</select>\n");
document.write("<input type=\"button\" id=\"domain-search\" name=\"search\" value=\"🔍 Search\"><br />\n");
document.write("<span id=\"domain\">&nbsp;</span>\n");
document.write("<span id=\"result\">&nbsp;</span><br />\n");
document.write("</form>");
